name: api_dart
description: Backend Dart (Shelf) para gestão de ferramentas e instrumentos.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^3.2.0
  dotenv: ^4.2.0
  logging: ^1.3.0
  mongo_dart: ^0.10.5
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
